# tasks file
---
- name: Install Python | Include variables
  ansible.builtin.include_vars: "{{ item }}"
  with_first_found:
    - "_{{ ansible_distribution_release }}.yml"
    - "_{{ (ansible_distribution + '-' + ansible_distribution_major_version) | lower }}.yml"
    - "_{{ ansible_distribution | lower }}.yml"
    - "_{{ (ansible_os_family + '-' + ansible_distribution_major_version) | lower }}.yml"
    - _default.yml
  tags:
    - configuration

- name: Install Python | Create download directory
  ansible.builtin.file:
    path: "{{ downloads_path }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Install Python | Include installation tasks
  ansible.builtin.include_tasks: '{{ ansible_os_family | lower }}/main.yml'

- name: Install Python | Upgrade tools
  ansible.builtin.command: >
    /opt/python/{{ item }}/bin/pip install --upgrade \
    pip setuptools wheel
  loop: "{{ python_versions }}"
  register: command_result
  changed_when: "'Successfully installed' in command_result.stdout"
  tags:
    - python-install-upgrade-tools

- name: Install Python | Make available as a Jupyter Kernel
  when: python_jupyter_kernel
  tags:
    - python-install-jupyter-kernel
  block:
    - name: Install Python | Install ipykernel
      ansible.builtin.pip:
        executable: "/opt/python/{{ item }}/bin/pip"
        name: ipykernel
      loop: "{{ python_versions }}"

    - name: Install Python | Check if kernel.json exists
      ansible.builtin.stat:
        path: "/usr/local/share/jupyter/kernels/py{{ item }}/kernel.json"
      loop: "{{ python_versions }}"
      register: kernel_json

    - name: Install Python | Run ipykernel install
      ansible.builtin.command: >
        /opt/python/{{ item }}/bin/python -m ipykernel install \
          --name py{{ item }} --display-name "Python {{ item }}"
      loop: "{{ python_versions }}"
      loop_control:
        index_var: index
      register: command_result
      changed_when: kernel_json.results[index].stat.exists == false

- name: Install Python | Include Jupyter installation tasks
  ansible.builtin.include_tasks: './install-jupyter.yml'
  when: python_jupyter_install
