---
- name: Verify
  hosts: all
  pre_tasks:
    - name: Include vars
      ansible.builtin.include_vars: "{{ playbook_dir }}/../../tests/vars/main.yml"
  tasks:
    - name: Include tasks
      ansible.builtin.include_tasks: "{{ playbook_dir }}/../../tests/tasks/post.yml"
