---
- name: Verify
  hosts: all
  become: true
  pre_tasks:
    - name: Include vars
      include_vars: "{{ playbook_dir }}/../../tests/vars/main.yml"
  tasks:
    - name: Include tasks
      include: "{{ playbook_dir }}/../../tests/tasks/post.yml"
