---
- name: Install additional python versions | Install system dependencies
  ansible.builtin.apt:
    pkg: "{{ python_system_dependecies }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - python-install-system-dependecies

- name: Install additional python versions | Set release version
  ansible.builtin.set_fact:
    ubuntu_release: "{{ ansible_facts['distribution_version'] | replace('.', '') }}"
  when: ansible_facts['distribution'] == "Ubuntu"
  tags:
    - python-install-set-facts
    - python-install-setup-versions

- name: Install additional python versions | Download deb package
  ansible.builtin.get_url:
    url: "https://cdn.rstudio.com/python/ubuntu-{{ ubuntu_release }}/pkgs/python-{{ item }}_1_amd64.deb"
    dest: "/tmp/Python-{{ item }}.deb"
    mode: "0644"
  loop: "{{ python_versions }}"
  tags:
    - python-install-download-archives
    - python-install-setup-versions

- name: Install additional python versions | Install deb package
  ansible.builtin.apt:
    deb: "/tmp/Python-{{ item }}.deb"
  loop: "{{ python_versions }}"
  tags:
    - python-install-install-archives
    - python-install-setup-versions
