---
- name: Enable EPEL Next repository (RHEL 9)
  ansible.builtin.command:
    cmd: dnf config-manager --set-enabled crb
  changed_when: false

- name: Install EPEL Next release (RHEL 9)
  ansible.builtin.dnf:
    name: epel-next-release
    state: present

- name: Install libev-devel
  ansible.builtin.dnf:
    name: libev-devel
    state: present


- name: Install Python | Download rpm package
  ansible.builtin.get_url:
    url: "{{ python_download_url }}/python-{{ item }}-1-1.x86_64.rpm"
    dest: "{{ downloads_path }}/python-{{ item }}-1-1.x86_64.rpm"
    mode: "0644"
  loop: "{{ python_versions }}"
  tags:
    - python-install-download-archives
    - python-install-setup-versions

- name: Install Python | Install rpm package
  ansible.builtin.dnf:
    name:  "{{ downloads_path }}/python-{{ item }}-1-1.x86_64.rpm"
    disable_gpg_check: true
    state: present
  loop: "{{ python_versions }}"
  tags:
    - python-install-install-archives
    - python-install-setup-versions
