---

- name: Install python | Install dependecies
  ansible.builtin.yum:
    name: "{{ system_dependecies }}"

- name: Install python | Download rpm package
  ansible.builtin.get_url:
    url: "{{ python_download_url }}/python-{{ item }}-1-1.x86_64.rpm"
    dest: "{{ downloads_path }}/python-{{ item }}-1-1.x86_64.rpm"
    mode: "0644"
  loop: "{{ python_versions }}"
  tags:
    - python-install-download-archives
    - python-install-setup-versions

- name: Install python | Install rpm package
  ansible.builtin.yum:
    name:  "{{ downloads_path }}/python-{{ item }}-1-1.x86_64.rpm"
    disable_gpg_check: true
    state: present
  loop: "{{ python_versions }}"
  tags:
    - python-install-install-archives
    - python-install-setup-versions
