---
- name: Converge
  hosts: all
  become: true
  pre_tasks:
    - name: Include vars
      include_vars: "{{ playbook_dir }}/../../tests/vars/main.yml"
  tasks:
    - name: "Include ansible-python-install"
      include_role:
        name: "ansible-python-install"
